
GET http://localhost:3000/films

###

GET http://localhost:3000/films/?minimum-duration=120

###

post http://localhost:3000/films
Content-Type: application/json

{
    "title": "Something",
    "director": "Somebody",
    "duration": 100
}